apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - certificate-hoppscotch-admin.yaml
  - certificate-hoppscotch-frontend.yaml
  - certificate-hoppscotch-backend.yaml
