apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: jwt-session-secrets
  namespace: hoppscotch
spec:
  encryptedData:
    JWT_SECRET: TODO
    SESSION_SECRET: TODO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: jwt-session-secrets
      namespace: hoppscotch
    type: Opaque
