apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoppscotch-frontend
spec:
  selector:
    matchLabels:
      app: hoppscotch-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: hoppscotch-frontend
    spec:
      containers:
        - name: hoppscotch-frontend
          image: hoppscotch-frontend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 5
            initialDelaySeconds: 10
            periodSeconds: 120
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: PRODUCTION
              value: "true"
            - name: VITE_ALLOWED_AUTH_PROVIDERS
              value: "GOOGLE,GITHUB,MICROSOFT,EMAIL"
            - name: REDIRECT_URL
              value: $(FRONTEND_URL_FULL)
            - name: WHITELISTED_ORIGINS
              value: $(WHITELISTED_ORIGINS)
            # Base URLs
            - name: VITE_BASE_URL
              value: $(FRONTEND_URL_FULL)
            - name: VITE_SHORTCODE_BASE_URL
              value: $(FRONTEND_URL_FULL)
            - name: VITE_ADMIN_URL
              value: $(ADMIN_URL_FULL)
            # Backend URLs
            - name: VITE_BACKEND_GQL_URL
              value: $(BACKEND_GQL_URL)
            - name: VITE_BACKEND_WS_URL
              value: $(BACKEND_WS_URL)
            - name: VITE_BACKEND_API_URL
              value: $(BACKEND_API_URL)
            # Terms Of Service And Privacy Policy Links (Optional)
            - name: VITE_APP_TOS_LINK
              value: "https://docs.hoppscotch.io/terms"
            - name: VITE_APP_PRIVACY_POLICY_LINK
              value: "https://docs.hoppscotch.io/privacy"
