apiVersion: v1
kind: Service
metadata:
  name: hoppscotch-postgresql
spec:
  selector:
    app: hoppscotch-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
