apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: development

resources:
  - ../../../base

configMapGenerator:
  - name: vars
    behavior: merge
    literals:
      - HOPPSCOTCH_ADMIN_URL="TODO"
      - HOPPSCOTCH_BACKEND_URL="TODO"
      - HOPPSCOTCH_FRONTEND_URL="TODO"
