apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: development

resources:
  - ../../../base
  - resources

configMapGenerator:
  - name: vars
    behavior: merge
    literals:
      - HOPPSCOTCH_ADMIN_URL="TODO"
      - HOPPSCOTCH_BACKEND_URL="TODO"
      - HOPPSCOTCH_FRONTEND_URL="TODO"
      - FRONTEND_URL_FULL="TODO"
      - ADMIN_URL_FULL="TODO"
      - BACKEND_URL_FULL="TODO"
      - BACKEND_GQL_URL="TODO"
      - BACKEND_WS_URL="TODO"
      - BACKEND_API_URL="TODO"
      - GOOGLE_CALLBACK_URL="TODO"
      - GITHUB_CALLBACK_URL="TODO"
      - MICROSOFT_CALLBACK_URL="TODO"
      - WHITELISTED_ORIGINS="TODO"
