apiVersion: v1
kind: Pod
metadata:
  name: db-restore-from-backup
spec:
  containers:
    - name: pvc-access
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: temp-pvc-access
          mountPath: /backups
  volumes:
    - name: temp-pvc-access
      persistentVolumeClaim:
        claimName: postgresql-backup-pvc
