apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hoppscotch

resources:
  - deployment-admin.yaml
  - service-admin.yaml
  - gateway-admin.yaml
  - virtualservice-admin.yaml
  - auth-policy-allow-admin.yaml
