apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hoppscotch

resources:
  - sealed-secrets/jwt-session-secrets.yaml
  - sealed-secrets/microsoft-auth.yaml
  - sealed-secrets/hoppscotch-statefulset-db-auth.yaml
